"""Canonical authority registry for Economy Lab engine composition.

v2.8 freezes an explicit answer to a question that previously lived mostly in
comments/documentation: *which engine is allowed to own each critical value?*

The registry separates realized state from advisory signals. External engines
never receive permission to mutate ledger balances or realized macro outcomes.
An :class:`AuthoritySession` records the active ownership plan and rejects
unauthorized or duplicate claims before they can be treated as canonical.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Iterable, Literal

from economy_lab.core.schemas import ScenarioSpec
from economy_lab.core.state import EconomyState


AUTHORITY_REGISTRY_VERSION = "1.0"
Cadence = Literal["run", "tick"]


class AuthorityError(RuntimeError):
    """Base error for authority-contract violations."""


class UnknownAuthorityFieldError(AuthorityError):
    pass


class UnauthorizedWriteError(AuthorityError):
    pass


class AuthorityConflictError(AuthorityError):
    pass


class MissingAuthorityClaimError(AuthorityError):
    pass


@dataclass(frozen=True, slots=True)
class VariableAuthorityContract:
    field: str
    allowed_sources: tuple[str, ...]
    cadence: Cadence
    description: str
    category: str


@dataclass(frozen=True, slots=True)
class AuthorityAssignment:
    field: str
    source: str
    cadence: Cadence
    description: str
    category: str


@dataclass(frozen=True, slots=True)
class AuthorityClaim:
    field: str
    source: str
    tick: int | None
    value: Any = None


@dataclass(slots=True)
class AuthorityAudit:
    registry_version: str
    strict: bool
    assignments: list[AuthorityAssignment]
    claims_by_source: dict[str, int]
    claims_by_field: dict[str, int]
    total_claims: int
    violations: list[str]
    complete: bool

    @property
    def status(self) -> str:
        return "pass" if self.complete and not self.violations else "fail"

    def to_dict(self) -> dict[str, object]:
        return {
            "registry_version": self.registry_version,
            "strict": self.strict,
            "status": self.status,
            "complete": self.complete,
            "total_claims": self.total_claims,
            "claims_by_source": dict(sorted(self.claims_by_source.items())),
            "claims_by_field": dict(sorted(self.claims_by_field.items())),
            "violations": list(self.violations),
            "assignments": [
                {
                    "field": item.field,
                    "source": item.source,
                    "cadence": item.cadence,
                    "description": item.description,
                    "category": item.category,
                }
                for item in self.assignments
            ],
        }


# Static capability contract. A scenario activates exactly one source from each
# applicable multi-source contract.
AUTHORITY_CONTRACTS: tuple[VariableAuthorityContract, ...] = (
    VariableAuthorityContract(
        "activation.agent_order_policy", ("native_activation", "mesa"), "run",
        "Agent activation/order policy. Mesa may order agents but owns no balances.", "agents",
    ),
    VariableAuthorityContract(
        "household.consumption_policy", ("native_heuristic", "hark"), "run",
        "Desired household consumption policy. Realized payments remain ledger-owned.", "households",
    ),
    VariableAuthorityContract(
        "macro.structural_irf", ("dynare",), "run",
        "Structural macro IRF/guidance produced by Dynare; never realized GDP.", "macro_guidance",
    ),
    VariableAuthorityContract(
        "financial.control_policy", ("native_finance", "minsky_profile"), "run",
        "Banking control path (capital/reserve/credit/spreads), not financial balances.", "financial_guidance",
    ),
    VariableAuthorityContract(
        "macro.applied_policy_rate", ("scenario_central_bank", "hybrid_coupler"), "tick",
        "Policy rate actually applied to Economy Zero for the month.", "policy",
    ),
    VariableAuthorityContract(
        "macro.realized_gdp", ("economy_zero_abm",), "tick",
        "Realized GDP/output generated by the Economy Zero economy.", "realized_macro",
    ),
    VariableAuthorityContract(
        "macro.realized_inflation", ("economy_zero_abm",), "tick",
        "Realized inflation generated by the Economy Zero price system.", "realized_macro",
    ),
    VariableAuthorityContract(
        "macro.realized_unemployment", ("economy_zero_abm",), "tick",
        "Realized unemployment generated by labor-market matching/separations.", "realized_macro",
    ),
    VariableAuthorityContract(
        "production.productive_capital", ("economy_zero_abm",), "tick",
        "Real productive-capital stock; not a financial Godley instrument.", "real_economy",
    ),
    VariableAuthorityContract(
        "financial.bank_deposits", ("ledger_sfc",), "tick",
        "Canonical bank deposit positions from the transaction ledger.", "financial_state",
    ),
    VariableAuthorityContract(
        "financial.bank_credit", ("ledger_sfc",), "tick",
        "Canonical bank-credit assets/liabilities from the transaction ledger.", "financial_state",
    ),
    VariableAuthorityContract(
        "financial.bank_reserves", ("ledger_sfc",), "tick",
        "Canonical reserve positions settled through the ledger.", "financial_state",
    ),
    VariableAuthorityContract(
        "financial.household_debt", ("ledger_sfc",), "tick",
        "Canonical household debt from ledger loan instruments.", "financial_state",
    ),
    VariableAuthorityContract(
        "financial.corporate_debt", ("ledger_sfc",), "tick",
        "Canonical corporate debt from ledger loan instruments.", "financial_state",
    ),
    VariableAuthorityContract(
        "financial.government_debt", ("ledger_sfc",), "tick",
        "Canonical government debt from SFC/Godley instruments.", "financial_state",
    ),
    VariableAuthorityContract(
        "financial.bank_capital", ("ledger_sfc",), "tick",
        "Canonical regulatory-capital position derived from bank balance sheets.", "financial_state",
    ),
)

_CONTRACT_BY_FIELD = {item.field: item for item in AUTHORITY_CONTRACTS}


def list_authority_contracts() -> tuple[VariableAuthorityContract, ...]:
    return AUTHORITY_CONTRACTS


def _activation_source(spec: ScenarioSpec) -> str:
    return "mesa" if spec.activation_engine == "mesa" else "native_activation"


def _household_source(spec: ScenarioSpec) -> str:
    return "hark" if spec.household_behavior == "hark" else "native_heuristic"


def _financial_source(spec: ScenarioSpec) -> str:
    return "minsky_profile" if spec.financial_engine == "minsky_profile" else "native_finance"


def _policy_source(spec: ScenarioSpec) -> str:
    return (
        "hybrid_coupler"
        if spec.macro_engine == "dynare" and spec.macro_coupling == "hybrid"
        else "scenario_central_bank"
    )


def build_authority_assignments(spec: ScenarioSpec) -> tuple[AuthorityAssignment, ...]:
    """Resolve the active owner of every canonical field for *spec*.

    Dynare's structural IRF contract is inactive when macro_engine=off. All
    realized macro and financial state contracts remain active in Economy Zero.
    """

    selected: dict[str, str | None] = {
        "activation.agent_order_policy": _activation_source(spec),
        "household.consumption_policy": _household_source(spec),
        "macro.structural_irf": "dynare" if spec.macro_engine == "dynare" else None,
        "financial.control_policy": _financial_source(spec),
        "macro.applied_policy_rate": _policy_source(spec),
        "macro.realized_gdp": "economy_zero_abm",
        "macro.realized_inflation": "economy_zero_abm",
        "macro.realized_unemployment": "economy_zero_abm",
        "production.productive_capital": "economy_zero_abm",
        "financial.bank_deposits": "ledger_sfc",
        "financial.bank_credit": "ledger_sfc",
        "financial.bank_reserves": "ledger_sfc",
        "financial.household_debt": "ledger_sfc",
        "financial.corporate_debt": "ledger_sfc",
        "financial.government_debt": "ledger_sfc",
        "financial.bank_capital": "ledger_sfc",
    }
    assignments: list[AuthorityAssignment] = []
    for field_name, source in selected.items():
        if source is None:
            continue
        contract = _CONTRACT_BY_FIELD[field_name]
        if source not in contract.allowed_sources:
            raise UnauthorizedWriteError(
                f"Authority plan selected {source!r} for {field_name!r}, "
                f"allowed={contract.allowed_sources!r}"
            )
        assignments.append(
            AuthorityAssignment(
                field=field_name,
                source=source,
                cadence=contract.cadence,
                description=contract.description,
                category=contract.category,
            )
        )
    return tuple(assignments)


class AuthoritySession:
    """Strict runtime audit for one simulation.

    A claim is accepted only when the source matches the scenario's resolved
    owner. A field can be claimed once per cadence key (once per run or once per
    tick). This deliberately rejects silent overwrites, including overwrites by
    the same engine.
    """

    def __init__(self, spec: ScenarioSpec, *, strict: bool = True):
        self.spec = spec
        self.strict = bool(strict)
        self.assignments = build_authority_assignments(spec)
        self._assignment_by_field = {item.field: item for item in self.assignments}
        self._claims: dict[tuple[str, int | None], AuthorityClaim] = {}
        self._violations: list[str] = []

    def expected_source(self, field: str) -> str:
        assignment = self._assignment_by_field.get(field)
        if assignment is None:
            raise UnknownAuthorityFieldError(f"No active authority for field {field!r}")
        return assignment.source

    def assert_binding(self, field: str, actual_source: str) -> None:
        expected = self.expected_source(field)
        if actual_source != expected:
            message = f"Authority binding mismatch for {field}: expected {expected}, got {actual_source}"
            self._violations.append(message)
            if self.strict:
                raise UnauthorizedWriteError(message)

    def claim(self, field: str, source: str, *, tick: int | None = None, value: Any = None) -> None:
        contract = _CONTRACT_BY_FIELD.get(field)
        if contract is None:
            message = f"Unknown canonical field {field!r}"
            self._violations.append(message)
            if self.strict:
                raise UnknownAuthorityFieldError(message)
            return
        assignment = self._assignment_by_field.get(field)
        if assignment is None:
            message = f"Field {field!r} is inactive in this scenario; {source!r} attempted a claim"
            self._violations.append(message)
            if self.strict:
                raise UnauthorizedWriteError(message)
            return
        if source != assignment.source:
            message = f"Unauthorized authority claim for {field}: expected {assignment.source}, got {source}"
            self._violations.append(message)
            if self.strict:
                raise UnauthorizedWriteError(message)
            return
        cadence_tick = None if assignment.cadence == "run" else tick
        if assignment.cadence == "tick" and (tick is None or int(tick) < 1):
            message = f"Tick-scoped authority field {field!r} requires tick >= 1"
            self._violations.append(message)
            if self.strict:
                raise AuthorityConflictError(message)
            return
        key = (field, cadence_tick)
        previous = self._claims.get(key)
        if previous is not None:
            message = (
                f"Duplicate canonical write for {field} at "
                f"{'run' if cadence_tick is None else f'tick {cadence_tick}'}: "
                f"first={previous.source}, second={source}"
            )
            self._violations.append(message)
            if self.strict:
                raise AuthorityConflictError(message)
            return
        self._claims[key] = AuthorityClaim(field=field, source=source, tick=cadence_tick, value=value)

    def claim_run_bindings(
        self,
        *,
        activation_source: str,
        household_source: str,
        financial_source: str,
        dynare_active: bool,
    ) -> None:
        self.assert_binding("activation.agent_order_policy", activation_source)
        self.claim("activation.agent_order_policy", activation_source, value=activation_source)
        self.assert_binding("household.consumption_policy", household_source)
        self.claim("household.consumption_policy", household_source, value=household_source)
        self.assert_binding("financial.control_policy", financial_source)
        self.claim("financial.control_policy", financial_source, value=financial_source)
        if dynare_active:
            self.assert_binding("macro.structural_irf", "dynare")
            self.claim("macro.structural_irf", "dynare", value="dynare-reference-nk")

    def claim_tick(self, *, state: EconomyState) -> None:
        tick = state.tick
        policy_source = state.decisions.macro_policy_source
        self.assert_binding("macro.applied_policy_rate", policy_source)
        self.claim("macro.applied_policy_rate", policy_source, tick=tick, value=state.macro.policy_rate)
        self.claim("macro.realized_gdp", "economy_zero_abm", tick=tick, value=state.macro.gdp)
        self.claim("macro.realized_inflation", "economy_zero_abm", tick=tick, value=state.macro.inflation)
        self.claim("macro.realized_unemployment", "economy_zero_abm", tick=tick, value=state.macro.unemployment)
        self.claim("production.productive_capital", "economy_zero_abm", tick=tick, value=state.real.productive_capital)
        self.claim("financial.bank_deposits", "ledger_sfc", tick=tick, value=state.financial.bank_deposits)
        self.claim("financial.bank_credit", "ledger_sfc", tick=tick, value=state.financial.bank_credit)
        self.claim("financial.bank_reserves", "ledger_sfc", tick=tick, value=state.financial.bank_reserves)
        self.claim("financial.household_debt", "ledger_sfc", tick=tick, value=state.financial.household_debt)
        self.claim("financial.corporate_debt", "ledger_sfc", tick=tick, value=state.financial.corporate_debt)
        self.claim("financial.government_debt", "ledger_sfc", tick=tick, value=state.financial.government_debt)
        self.claim("financial.bank_capital", "ledger_sfc", tick=tick, value=state.financial.bank_capital)

    def assert_complete(self, ticks: int) -> None:
        missing: list[str] = []
        for assignment in self.assignments:
            if assignment.cadence == "run":
                if (assignment.field, None) not in self._claims:
                    missing.append(f"{assignment.field}@run")
            else:
                for tick in range(1, ticks + 1):
                    if (assignment.field, tick) not in self._claims:
                        missing.append(f"{assignment.field}@{tick}")
        if missing:
            message = "Missing canonical authority claims: " + ", ".join(missing[:20])
            if len(missing) > 20:
                message += f" (+{len(missing) - 20} more)"
            self._violations.append(message)
            if self.strict:
                raise MissingAuthorityClaimError(message)

    def audit(self, *, ticks: int) -> AuthorityAudit:
        complete = True
        try:
            self.assert_complete(ticks)
        except MissingAuthorityClaimError:
            complete = False
        claims_by_source: dict[str, int] = {}
        claims_by_field: dict[str, int] = {}
        for claim in self._claims.values():
            claims_by_source[claim.source] = claims_by_source.get(claim.source, 0) + 1
            claims_by_field[claim.field] = claims_by_field.get(claim.field, 0) + 1
        return AuthorityAudit(
            registry_version=AUTHORITY_REGISTRY_VERSION,
            strict=self.strict,
            assignments=list(self.assignments),
            claims_by_source=claims_by_source,
            claims_by_field=claims_by_field,
            total_claims=len(self._claims),
            violations=list(self._violations),
            complete=complete and not self._violations,
        )


def runtime_source_from_activation_name(name: str) -> str:
    return "mesa" if str(name).startswith("mesa") else "native_activation"


def runtime_source_from_household_name(name: str) -> str:
    return "hark" if str(name).startswith("hark") else "native_heuristic"


def authority_registry_payload() -> list[dict[str, object]]:
    return [
        {
            "field": item.field,
            "allowed_sources": list(item.allowed_sources),
            "cadence": item.cadence,
            "description": item.description,
            "category": item.category,
        }
        for item in AUTHORITY_CONTRACTS
    ]


def authority_plan_payload(spec: ScenarioSpec) -> list[dict[str, object]]:
    return [
        {
            "field": item.field,
            "source": item.source,
            "cadence": item.cadence,
            "description": item.description,
            "category": item.category,
        }
        for item in build_authority_assignments(spec)
    ]
